db:
  collection: documents
  name: MAI_search_corpus
  url: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.5.8
logic:
  accessable_pages:
  - https://www.billboard.com/c/music/
  - https://www.billboard.com/music/
  - https://pitchfork.com/news/
  delay: 5
  max_depth: 30000
  parseable_pages:
  - https://www.billboard.com/music/
  - https://pitchfork.com/news/
  start_id: 30051
  start_url: https://pitchfork.com/news/?page=50